language: scala
scala:
  - 2.12.10

# Dependencies for Verilator
addons:
  apt:
    packages:
      - make
      - autoconf
      - g++
      - flex
      - bison

install:
  - export FILE="riscv64-unknown-elf-gcc-2018.07.0-x86_64-linux-ubuntu14"
  - wget https://static.dev.sifive.com/dev-tools/$FILE.tar.gz
  - tar xf $FILE.tar.gz
  - export PATH=$PATH:$PWD/$FILE/bin

script:
  - tools/install-verilator.sh
  - export PATH=$PATH:$PWD/tmp/bin
  - make -C test_asm
  - sbt test
  - sbt run
